(function () {
  "use strict";

  if (typeof CASES === "undefined" || typeof TASKS === "undefined") return;

  const scenario = (
    profile,
    presentation,
    participation,
    environment,
    complexity,
    reviewFocus,
    evidenceKey,
    icfFrame,
    precautions,
    team,
  ) => ({
    cohort: "Alternative evidence-informed cohort",
    profile,
    presentation,
    participation,
    environment,
    complexity,
    reviewFocus,
    evidenceKey,
    icfFrame,
    precautions,
    team,
  });

  const diverseCases = [
    [
      "Case 37 · Stroke Midline Control",
      "Stroke",
      "Inpatient rehabilitation",
      "Balance",
      "In progress",
      "Regain stable midline sitting and standing for safer bed-to-chair transfers.",
      "Reduce directional pushing and manual assistance. Sample protocol: repeated task-specific alignment, visual-reference feedback, transfer components and cue-fading across ward contexts.",
      165,
      620,
      "Postural Assessment Scale for Stroke",
      "14 points",
      "20 points",
      "28 points",
      scenario(
        "Older adult in the early inpatient phase after a right-hemisphere stroke, medically stable and able to follow one-step instructions.",
        "Marked asymmetry in sitting and standing, inconsistent awareness of upright alignment and two-person assistance for some transfers.",
        "The immediate priority is to sit safely for dressing and complete transfers with one trained helper before discharge planning.",
        "Performance improves with a mirror and firm foot support but deteriorates when the room is busy or cues change between staff.",
        "Visual-spatial impairment, fatigue and variable cueing make raw repetition counts an incomplete marker of progress.",
        "Compare assistance, alignment quality and transfer carryover across staff and settings before interpreting the trajectory.",
        "stroke",
        "Body function: postural orientation; activity: sitting and transfer control; participation: morning self-care and discharge destination; environment: cue consistency and seating setup.",
        "Use the documented transfer plan, monitor loss of balance and stop or re-grade if alertness or postural control changes.",
        "Inpatient stroke multidisciplinary team",
      ),
    ],
    [
      "Case 38 · Stroke Sensory Hand",
      "Stroke",
      "Outpatient",
      "Upper limb",
      "Improving",
      "Use the affected hand to locate, stabilise and manipulate household objects with less visual monitoring.",
      "Improve sensory discrimination and bimanual task confidence. Sample protocol: graded object identification, reach-grasp practice, bilateral household tasks and structured home feedback.",
      135,
      780,
      "Patient-specific hand task rating",
      "2/10",
      "5/10",
      "8/10",
      scenario(
        "Working-age adult several months after stroke with useful voluntary hand movement and persistent altered touch and position sense.",
        "Grip force is adequate for light objects, but the hand is visually monitored and small items are dropped when attention is divided.",
        "The person wants to prepare lunch, organise medication packaging and use a laptop with both hands.",
        "Home practice is feasible at a kitchen table; contrasting objects and family feedback are available, but time is limited on workdays.",
        "Motor capacity can mask sensory-related safety and efficiency problems, so task conditions and visual dependence need explicit recording.",
        "Review object type, vision available, error pattern, compensation and daily-task transfer alongside valid repetitions.",
        "stroke",
        "Body function: somatosensory processing and hand control; activity: object manipulation; participation: domestic and work tasks; environment: object contrast and practice support.",
        "Use safe, non-sharp practice objects and clinician-selected sensory tasks; review skin integrity and unexpected sensory change.",
        "Outpatient neurorehabilitation team",
      ),
    ],
    [
      "Case 39 · Stroke Community Transit",
      "Stroke",
      "Community",
      "Mixed programme",
      "In progress",
      "Complete a familiar public-transport journey with planned rest, safe boarding and independent route checks.",
      "Integrate mobility, communication and executive strategies. Sample protocol: staged route planning, simulated boarding, community walking intervals and supported real-world rehearsal.",
      150,
      540,
      "Life-Space Assessment",
      "28 points",
      "42 points",
      "65 points",
      scenario(
        "Working-age adult in community rehabilitation after stroke, walking with a stick and using a phone-based reminder system.",
        "Indoor mobility is independent, while time pressure, route changes and divided attention reduce safety and confidence outdoors.",
        "The person aims to resume a weekly community role and attend appointments without relying on family transport.",
        "The route includes a lift, a short crossing, bus boarding and variable seating; off-peak practice and a travel companion are initially available.",
        "Mobility, fatigue, communication and executive demands interact, so a clinic walking result alone cannot represent readiness.",
        "Track cueing, route accuracy, rest strategy, environmental complexity and recovery after the journey.",
        "stroke",
        "Body function: endurance and executive control; activity: community walking and route navigation; participation: volunteering and healthcare access; environment: transit design and support.",
        "Community trials require clinician-approved risk planning, appropriate mobility aids and review of crossing and boarding safety.",
        "Community stroke rehabilitation team",
      ),
    ],
    [
      "Case 40 · SCI Technology Access",
      "Spinal cord injury",
      "Inpatient rehabilitation",
      "ADL / participation",
      "In progress",
      "Operate a power chair, phone and call system reliably using an individualised access method.",
      "Improve setup consistency and reduce caregiver-dependent repositioning. Sample protocol: access trials, switch timing, supported reach and repeated setup checks across daily contexts.",
      125,
      420,
      "SCIM self-care",
      "3 points",
      "6 points",
      "10 points",
      scenario(
        "Adult with recent cervical spinal cord injury participating in specialist inpatient rehabilitation.",
        "Proximal upper-limb movement is emerging, hand function is limited and device access varies with seating and fatigue.",
        "Priorities are independent environmental control, private communication and reliable access to staff assistance.",
        "A power chair, mounted phone and alternative switches are available; positioning changes between bed and chair alter performance.",
        "Small setup differences can determine success, while high attempt counts may increase fatigue without improving functional access.",
        "Compare access accuracy, time, seating configuration, assistance and sustained use in real routines.",
        "sci",
        "Body function: upper-limb control and endurance; activity: technology access; participation: communication and environmental control; environment: seating, mounts and caregiver setup.",
        "Follow specialist seating, skin, autonomic and upper-limb protection plans; stop if new symptoms or equipment concerns arise.",
        "Specialist spinal rehabilitation team",
      ),
    ],
    [
      "Case 41 · SCI Morning Routine",
      "Spinal cord injury",
      "Subacute",
      "Mixed programme",
      "Improving",
      "Complete the morning mobility and dressing sequence within a sustainable effort window.",
      "Improve transfer efficiency and self-directed rest planning. Sample protocol: task analysis, transfer components, upper-limb conditioning and timed routine rehearsal with recovery monitoring.",
      145,
      560,
      "SCIM mobility",
      "10 points",
      "14 points",
      "19 points",
      scenario(
        "Adult with incomplete thoracic spinal cord injury transitioning from inpatient to home-based rehabilitation.",
        "Transfers are completed with a board and supervision, but a full morning routine produces marked fatigue and delays later activities.",
        "The person wants to prepare independently for remote work and preserve energy for parenting responsibilities.",
        "The home has adequate turning space but a different bed height from the rehabilitation unit; a family member can assist at planned times.",
        "Efficiency, equipment setup and recovery time matter more than isolated peak performance.",
        "Review sequence duration, assistance, active contribution, rest distribution and next-activity tolerance.",
        "sci",
        "Body function: strength and endurance; activity: transfers and dressing; participation: work and family roles; environment: bed height, transfer equipment and scheduled support.",
        "Respect the documented transfer, skin and autonomic plans; review shoulder symptoms and avoid unplanned progression of assistance level.",
        "Spinal transition rehabilitation team",
      ),
    ],
    [
      "Case 42 · SCI Community Wheelchair",
      "Spinal cord injury",
      "Community",
      "Functional task practice",
      "In progress",
      "Navigate common community surfaces and entrances using efficient wheelchair skills.",
      "Improve route choice and shoulder-load management. Sample protocol: graded surface practice, doorway and ramp sequencing, propulsion feedback and community carryover review.",
      140,
      660,
      "Wheelchair Skills Test",
      "52%",
      "64%",
      "82%",
      scenario(
        "Adult wheelchair user with stable spinal cord injury beginning independent community mobility training.",
        "Indoor propulsion is independent, while slopes, uneven paving and narrow doors require cueing or physical assistance.",
        "The person wants to use nearby shops and attend a community course without a companion for the whole journey.",
        "Routes differ in gradient and accessibility; chair configuration is stable, and transport links can be tested at quieter times.",
        "Skill success must be considered with safety, efficiency, shoulder response and access barriers rather than a binary completion score.",
        "Record surface, gradient, cueing, attempts, propulsion quality, symptoms and successful route adaptations.",
        "wheelchair",
        "Body function: upper-limb endurance and trunk control; activity: wheelchair mobility; participation: shopping and education; environment: gradients, entrances and transport.",
        "Use trained supervision and the person-specific wheelchair plan; do not practise unapproved high-risk obstacles.",
        "Community wheelchair and rehabilitation service",
      ),
    ],
    [
      "Case 43 · TBI Return to Study",
      "Traumatic brain injury",
      "Community",
      "Cognition",
      "In progress",
      "Complete a structured study block and retain key information without a prolonged symptom increase.",
      "Improve pacing, planning and self-monitoring. Sample protocol: brief study simulations, external memory supports, scheduled recovery and graded campus-task rehearsal.",
      105,
      360,
      "Goal Attainment Scaling",
      "-2",
      "-1",
      "+1",
      scenario(
        "Young adult in community rehabilitation after moderate traumatic brain injury, preparing for a staged return to tertiary study.",
        "Basic attention is adequate in quiet settings, but longer reading, competing noise and rapid instructions increase fatigue and errors.",
        "The person prioritises attending one class, managing notes and completing a short assignment with agreed accommodations.",
        "A quiet study space and digital planner are available; travel and crowded teaching spaces add cognitive load.",
        "Capacity varies by task duration and environment, and performance may decline later rather than during the practice block.",
        "Track task complexity, support used, errors noticed, recovery time and next-day participation.",
        "tbi",
        "Body function: attention, memory and fatigue; activity: studying and note management; participation: education; environment: noise, travel and accommodations.",
        "Use the specialist return-to-study plan, respect symptom-limited boundaries and escalate unexpected neurological or functional change.",
        "Acquired brain injury community team",
      ),
    ],
    [
      "Case 44 · TBI Workday Pacing",
      "Traumatic brain injury",
      "Community",
      "Cognition",
      "Plateauing",
      "Sustain a half-day work simulation using planned breaks and accurate task handover.",
      "Reduce unplanned task switching and late-day error accumulation. Sample protocol: workload mapping, timed work blocks, checklist use and structured fatigue review.",
      100,
      300,
      "Work participation rating",
      "3/10",
      "4/10",
      "7/10",
      scenario(
        "Working-age adult in later-stage rehabilitation after traumatic brain injury, trialling a supported return to an administrative role.",
        "Routine single tasks are accurate, but interruptions and self-imposed time pressure lead to missed steps and disproportionate fatigue.",
        "The shared goal is a predictable half-day schedule with reliable handover and energy remaining for essential home activities.",
        "The employer can provide a quieter workstation, written priorities and flexible hours; commuting adds an unmeasured demand.",
        "A plateau in clinic tasks may not reflect real-world executive load, and overactivity on a good day can distort weekly averages.",
        "Compare planned versus actual breaks, accuracy, interruptions, fatigue recovery and home participation.",
        "tbi",
        "Body function: executive control and fatigue; activity: sustained work tasks; participation: employment and home life; environment: interruptions, accommodations and commute.",
        "Keep changes within the agreed vocational plan and review marked symptom escalation, safety-sensitive errors or reduced recovery.",
        "Neuro-vocational rehabilitation team",
      ),
    ],
    [
      "Case 45 · ABI Kitchen Executive",
      "Traumatic brain injury",
      "Outpatient",
      "ADL / participation",
      "Improving",
      "Prepare a simple meal using a safe sequence and an external checklist with minimal cueing.",
      "Improve error detection and divided-attention management. Sample protocol: task analysis, low-risk kitchen simulation, checklist fading and supported home transfer.",
      120,
      390,
      "COPM performance",
      "3/10",
      "5/10",
      "8/10",
      scenario(
        "Adult with acquired executive and memory difficulties after traumatic brain injury, living with family during outpatient rehabilitation.",
        "Individual preparation steps are physically manageable, but sequence omissions and distraction occur when two items are active.",
        "Independent breakfast and one evening meal are meaningful milestones for shared household participation.",
        "The home kitchen is compact and familiar; visual labels and a timer are acceptable, with family available for planned oversight.",
        "Completion time alone can hide cueing, safety checks and error correction, so qualitative observation is essential.",
        "Review sequence accuracy, cue level, hazards identified, support use and transfer from clinic simulation to home.",
        "tbi",
        "Body function: executive control and prospective memory; activity: meal preparation; participation: household role; environment: kitchen layout, prompts and family oversight.",
        "Use only clinician-approved low-risk tasks and the documented supervision level; source safety assessment remains authoritative.",
        "Occupational therapy and neuropsychology team",
      ),
    ],
    [
      "Case 46 · Adult CP Mobility Transition",
      "Cerebral palsy",
      "Chronic / long-term management",
      "Gait",
      "Revised",
      "Maintain reliable short-distance walking while introducing wheeled mobility for longer community journeys.",
      "Reduce fatigue-related participation loss. Sample protocol: walking-efficiency review, device trials, transfer practice and energy-aware journey planning.",
      115,
      480,
      "6MWT",
      "285 m",
      "270 m",
      "270 m",
      scenario(
        "Adult with bilateral cerebral palsy reporting increasing effort for community distances while retaining useful household walking.",
        "Walking quality declines with fatigue, and recovery after long outings limits work and social participation the following day.",
        "The person wants to preserve chosen walking while gaining a dependable option for longer journeys and workplace access.",
        "Home access is level; workplace distances are long, and storage or transport of a mobility device requires assessment.",
        "The goal is participation and sustainable choice rather than maximising one mobility mode or treating a lower walking distance as failure.",
        "Track journey purpose, device context, effort, recovery and participation across the whole day.",
        "adult-cp",
        "Body function: motor control and endurance; activity: walking and wheeled mobility; participation: employment and social life; environment: distance, storage and transport.",
        "Review pain, fatigue, falls, orthotic fit and equipment setup with the specialist team before changing mobility expectations.",
        "Adult cerebral palsy multidisciplinary team",
      ),
    ],
    [
      "Case 47 · Adult CP Assistive Access",
      "Cerebral palsy",
      "Home programme",
      "ADL / participation",
      "In progress",
      "Use electronic access for communication and home control across seating positions.",
      "Increase reliable selection and reduce setup burden. Sample protocol: access-method comparison, positioning checks, switch practice and communication-partner training.",
      95,
      320,
      "COPM satisfaction",
      "4/10",
      "6/10",
      "8/10",
      scenario(
        "Adult with dyskinetic cerebral palsy who uses supported seating and augmentative communication at home.",
        "Selection accuracy changes with posture, involuntary movement and fatigue; caregiver setup varies between morning and evening.",
        "Priorities are private messaging, independent media choice and reliable environmental control.",
        "Two seating systems and several access options are available, but mounting and partner training are inconsistent.",
        "Device accuracy is inseparable from posture, social interaction and setup time; reduced caregiver contact is not automatically a positive outcome.",
        "Review access accuracy, false selections, positioning, partner support, communication opportunity and satisfaction.",
        "adult-cp",
        "Body function: motor and communication control; activity: electronic access; participation: communication and choice; environment: seating, mounts and partner competence.",
        "Use rehabilitation-engineering recommendations, protect comfort and skin, and retain a dependable backup communication method.",
        "Assistive technology and adult CP team",
      ),
    ],
    [
      "Case 48 · Adult CP Community Fitness",
      "Cerebral palsy",
      "Community",
      "Mixed programme",
      "In progress",
      "Participate in an accessible community activity twice weekly with sustainable recovery.",
      "Build confidence in self-selected aerobic and strength activity. Sample protocol: accessible circuit orientation, pacing, transfer rehearsal and participation logging.",
      120,
      500,
      "Activity participation rating",
      "2/10",
      "5/10",
      "8/10",
      scenario(
        "Adult with cerebral palsy seeking a long-term community activity option after discharge from episodic therapy.",
        "Baseline strength supports daily transfers, while unfamiliar equipment, transport and fear of excessive fatigue reduce attendance.",
        "The desired outcome is regular enjoyable participation and maintenance of daily function, not a body-composition target.",
        "An accessible centre is available with staff orientation; evening transport and equipment transfer height remain barriers.",
        "Attendance, enjoyment, access and next-day function are as relevant as minutes or repetitions.",
        "Review chosen activity, assistance, perceived effort, recovery, access barriers and effect on daily tasks.",
        "adult-cp",
        "Body function: endurance and strength; activity: exercise participation and transfers; participation: recreation and community inclusion; environment: accessible equipment and transport.",
        "Use individually agreed activity boundaries and review pain, fatigue, tone changes or equipment concerns with the clinical team.",
        "Adult CP and community participation team",
      ),
    ],
    [
      "Case 49 · Parkinson Home Freezing",
      "Parkinson's disease",
      "Home programme",
      "Gait",
      "In progress",
      "Move safely between bedroom and bathroom using an agreed cueing strategy during low-light periods.",
      "Reduce start hesitation and rushed turning. Sample protocol: environmental setup, cue selection, doorway practice and caregiver-supported carryover at the relevant medication phase.",
      105,
      460,
      "TUG",
      "22 sec",
      "18 sec",
      "15 sec",
      scenario(
        "Older adult with Parkinson's disease and episodic freezing that is most problematic in a narrow home route.",
        "Clinic walking is relatively fluent, while initiation, turning and doorways at home require repeated attempts at some times of day.",
        "The person prioritises private, confident bathroom access without waking a family member for routine standby.",
        "The route has limited lighting, a loose rug already identified for review and space for one external cue option.",
        "Symptoms fluctuate with timing, attention and environment, so clinic averages can underestimate the functional problem.",
        "Record time context, cue used, freezing episodes, turn quality, assistance and near-fall reports.",
        "parkinson",
        "Body function: gait initiation and postural control; activity: short home walking; participation: private self-care; environment: doorway, lighting and cue availability.",
        "Follow the falls and medication-context plan; environmental changes and cueing require clinician and household agreement.",
        "Parkinson's multidisciplinary team",
      ),
    ],
    [
      "Case 50 · Parkinson Hand Function",
      "Parkinson's disease",
      "Outpatient",
      "Upper limb",
      "Improving",
      "Complete medication packaging, handwriting and fastener tasks with consistent amplitude and accuracy.",
      "Improve task setup and reduce late-task decrement. Sample protocol: high-amplitude reach and manipulation blocks, functional handwriting, fastener practice and home cueing.",
      115,
      640,
      "Patient-Specific Functional Scale",
      "3/10",
      "5/10",
      "8/10",
      scenario(
        "Adult with Parkinson's disease whose main limitation is reduced movement amplitude during fine daily tasks.",
        "Performance begins accurately but becomes smaller and slower across repeated writing, packaging and clothing tasks.",
        "Independent medication organisation and signing forms are higher priorities than a generic dexterity score.",
        "A stable table and adapted pen are available; task performance varies with time of day and divided attention.",
        "Repetition volume can look high despite progressive decrement, compensation or reduced task accuracy.",
        "Review amplitude, accuracy, time, cue dependence and function at the relevant daily time.",
        "parkinson",
        "Body function: movement amplitude and dexterity; activity: writing, packaging and dressing; participation: health management and administration; environment: tools and timing.",
        "Record medication context without altering it, and review pain, sudden functional change or unsafe medication handling with the treating team.",
        "Parkinson's occupational therapy team",
      ),
    ],
    [
      "Case 51 · Parkinson Dual-Task Social",
      "Parkinson's disease",
      "Community",
      "Mixed programme",
      "In progress",
      "Walk and communicate during a familiar community-group routine without losing stability or conversational participation.",
      "Improve self-selected prioritisation and cue use. Sample protocol: graded dual-task walking, turn practice, conversational rehearsal and community-context review.",
      135,
      560,
      "Dual-task TUG",
      "25 sec",
      "21 sec",
      "17 sec",
      scenario(
        "Adult with Parkinson's disease who attends a community group and finds walking while speaking increasingly difficult.",
        "Either gait or speech quality declines when both are required, especially during turns and when others set the pace.",
        "The person wants to remain socially engaged rather than choosing between mobility and conversation.",
        "The venue has predictable routes and seating, but arrival periods are crowded and acoustically demanding.",
        "Dual-task change may represent an adaptive prioritisation choice, so safety and participation need joint interpretation.",
        "Track task priority, gait stability, communication success, cueing, environment and confidence.",
        "parkinson",
        "Body function: motor-cognitive integration and voice; activity: walking while communicating; participation: social group; environment: crowding, pace and acoustics.",
        "Use clinician-selected dual-task challenge and preserve safe gait priority where required; review falls or swallowing/communication concerns separately.",
        "Parkinson's physiotherapy and speech team",
      ),
    ],
    [
      "Case 52 · MS Cognitive Pacing",
      "Multiple sclerosis",
      "Community",
      "Cognition",
      "In progress",
      "Complete essential work-planning tasks using a sustainable cognitive pacing routine.",
      "Reduce late-day omissions and next-day participation loss. Sample protocol: priority mapping, timed focus blocks, external reminders and fatigue-context review.",
      90,
      280,
      "Goal Attainment Scaling",
      "-2",
      "-1",
      "+1",
      scenario(
        "Working-age adult with multiple sclerosis reporting cognitive fatigue and variable processing speed during hybrid work.",
        "Accuracy is adequate early in a task, but long video meetings and rapid switching lead to missed follow-up actions.",
        "The goal is reliable completion of essential planning work while preserving energy for household and social roles.",
        "Home work allows quiet periods; office days add travel, temperature variation and unplanned interruptions.",
        "Day-to-day variability means a single high-performing session should not drive progression or prediction.",
        "Review task load, environment, heat/stress context, strategies used, recovery and next-day function.",
        "ms",
        "Body function: processing speed and fatigue; activity: planning and task switching; participation: employment and home roles; environment: hybrid work, heat and interruptions.",
        "Respect individually agreed fatigue boundaries and refer new or sustained neurological change to the treating MS team.",
        "MS occupational therapy and vocational team",
      ),
    ],
    [
      "Case 53 · MS Wheelchair Transfers",
      "Multiple sclerosis",
      "Home programme",
      "ADL / participation",
      "Revised",
      "Complete essential home transfers using the most sustainable combination of technique, equipment and assistance.",
      "Reduce effort spikes and preserve caregiver safety. Sample protocol: transfer analysis, equipment setup, cue standardisation and good-day/bad-day planning.",
      100,
      360,
      "COPM performance",
      "4/10",
      "5/10",
      "7/10",
      scenario(
        "Adult with progressive multiple sclerosis using wheeled mobility and variable assistance for home transfers.",
        "Transfer ability fluctuates with fatigue and heat; an independent technique on some mornings is not reliable later in the day.",
        "Priorities are bathroom access, caregiver sustainability and retaining active participation in the task.",
        "A transfer aid is available, but bed and toilet heights differ and not all helpers use the same sequence.",
        "Independence is not the sole outcome; predictability, effort, assistance quality and caregiver load must be visible.",
        "Compare setup, contribution, assistance, fatigue, time of day and recovery across transfer types.",
        "ms",
        "Body function: strength, motor control and fatigue; activity: transfers; participation: self-care and home life; environment: equipment, surface height and caregiver technique.",
        "Use the assessed transfer method and trained assistance; review new weakness, falls, skin issues or caregiver strain promptly.",
        "MS, seating and community care team",
      ),
    ],
    [
      "Case 54 · MS Relapse Recovery",
      "Multiple sclerosis",
      "Subacute",
      "Gait",
      "Improving",
      "Re-establish safe household walking after a recent functional decline while monitoring variability.",
      "Improve foot clearance and activity tolerance. Sample protocol: short overground intervals, task-specific strengthening, rest planning and consistent-condition reassessment.",
      120,
      520,
      "Timed 25-Foot Walk",
      "12.4 sec",
      "10.1 sec",
      "8.2 sec",
      scenario(
        "Adult with relapsing multiple sclerosis referred after medical review of a recent mobility decline.",
        "Household walking has resumed with an aid, but foot clearance, confidence and endurance remain below the prior routine.",
        "The initial participation goal is safe movement between essential rooms before resuming longer community tasks.",
        "The home is accessible on one level; afternoon heat and fatigue affect performance more than morning sessions.",
        "Recovery, normal variability and measurement conditions can overlap, so change should not be attributed automatically.",
        "Record aid, time of day, temperature/fatigue context, assistance and post-session response.",
        "ms",
        "Body function: lower-limb control and fatigue; activity: household walking; participation: independent home routine; environment: aid, layout and temperature.",
        "Work within the treating team's relapse plan and escalate new, worsening or unexpected neurological change.",
        "MS multidisciplinary rehabilitation team",
      ),
    ],
    [
      "Case 55 · MND Communication Access",
      "Motor neurone disease",
      "Home programme",
      "Speech / swallowing",
      "Revised",
      "Maintain reliable communication across fatigue levels using speech and augmentative options.",
      "Reduce communication breakdowns and partner guesswork. Sample protocol: message banking workflow, access-method practice, partner training and backup-system rehearsal.",
      75,
      240,
      "Communication participation rating",
      "6/10",
      "6/10",
      "7/10",
      scenario(
        "Adult with motor neurone disease experiencing changing speech endurance and hand access across the day.",
        "Short speech remains understandable in quiet settings, while longer conversation and device selection slow with fatigue.",
        "Priorities are family conversation, healthcare decisions and reliable urgent communication.",
        "A tablet-based system and low-tech backup are available; partner confidence and mounting differ between rooms.",
        "Maintenance and timely adaptation are valid outcomes in a progressive condition; stable scores can conceal increasing support.",
        "Review intelligibility, access accuracy, fatigue, partner support, backup readiness and personally important communication.",
        "mnd",
        "Body function: speech and access endurance; activity: multimodal communication; participation: relationships and decision-making; environment: devices, mounts and trained partners.",
        "Coordinate changes with the specialist MND and speech team; preserve a reliable backup and review swallowing or respiratory concerns through the appropriate pathway.",
        "Specialist MND and communication team",
      ),
    ],
    [
      "Case 56 · MND Supported Transfers",
      "Motor neurone disease",
      "Chronic / long-term management",
      "ADL / participation",
      "Revised",
      "Maintain safe, comfortable participation in essential transfers using timely equipment and trained assistance.",
      "Reduce avoidable effort for the person and caregivers. Sample protocol: equipment trials, active-participation cues, caregiver rehearsal and routine review as needs change.",
      70,
      220,
      "ALSFRS-R mobility domain",
      "7 points",
      "6 points",
      "6 points",
      scenario(
        "Adult with motor neurone disease whose lower-limb and trunk weakness is changing transfer reliability.",
        "A standing transfer remains possible at selected times, but effort and assistance are rising and the method is no longer predictable.",
        "The person wants to remain actively involved in transfers while protecting comfort, dignity and caregiver sustainability.",
        "Home space allows a transfer aid, though equipment delivery, training and use across different rooms require coordination.",
        "Attempting to preserve an earlier technique may increase burden; equipment-supported participation can represent goal achievement.",
        "Track assistance, active contribution, comfort, caregiver effort, setup and changes across the day.",
        "mnd",
        "Body function: progressive strength and endurance change; activity: transfers; participation: self-care and family life; environment: equipment, space and trained caregivers.",
        "Use specialist moving-and-handling assessment and update promptly for changing strength, breathing, comfort or caregiver capacity.",
        "Specialist MND, community and equipment team",
      ),
    ],
    [
      "Case 57 · Neuromuscular Seating",
      "Neuromuscular condition",
      "Chronic / long-term management",
      "ADL / participation",
      "In progress",
      "Sustain supported sitting for learning, communication and powered mobility without losing later-day participation.",
      "Improve positioning consistency and energy conservation. Sample protocol: seating review, access practice, supported upper-limb tasks and caregiver setup training.",
      80,
      260,
      "COPM satisfaction",
      "4/10",
      "6/10",
      "8/10",
      scenario(
        "Young person with a neuromuscular condition transitioning to more complex powered seating and school access needs.",
        "Head and upper-limb endurance decrease over the day, affecting device access and classroom participation despite stable early-session performance.",
        "The person prioritises communication, computer use and joining lessons with peers for longer periods.",
        "School and home use different desk heights; staff training and access to tilt functions are inconsistent.",
        "A longer sitting duration is not beneficial if it reduces comfort, access or later participation.",
        "Review posture, pressure management, access quality, fatigue, position changes and participation across the day.",
        "neuromuscular",
        "Body function: postural and upper-limb endurance; activity: seated access; participation: education and communication; environment: powered seating, desk height and trained support.",
        "Follow specialist neuromuscular, respiratory, seating and skin-management plans; adjust only within assessed equipment parameters.",
        "Neuromuscular, seating and education team",
      ),
    ],
    [
      "Case 58 · Huntington Community Routine",
      "Huntington's disease",
      "Community",
      "Mixed programme",
      "In progress",
      "Complete a familiar local routine with safe pacing, clear sequencing and agreed support.",
      "Maintain mobility and reduce task breakdown under distraction. Sample protocol: consistent route rehearsal, simple cueing, balance tasks and caregiver communication.",
      105,
      420,
      "TUG",
      "19 sec",
      "18 sec",
      "17 sec",
      scenario(
        "Adult with Huntington's disease receiving community rehabilitation to maintain a meaningful weekly routine.",
        "Walking is independent in quiet spaces, while variable pace, reduced planning and distraction affect errands and transitions.",
        "The chosen goal is to continue visiting a nearby café with an agreed level of support.",
        "The route is short and familiar; busy periods, payment steps and seating transitions increase complexity.",
        "Stable speed does not show changes in cueing, judgement or participation, and support needs may change before the outcome score.",
        "Review route consistency, cueing, balance, task sequence, support and enjoyment.",
        "huntington",
        "Body function: motor control and executive function; activity: community mobility and transaction sequence; participation: social routine; environment: familiar route, crowding and support.",
        "Use the agreed community risk plan and review falls, swallowing, communication or behavioural change with the specialist team.",
        "Huntington's disease multidisciplinary team",
      ),
    ],
    [
      "Case 59 · Friedreich Ataxia Transfers",
      "Friedreich ataxia",
      "Outpatient",
      "Balance",
      "In progress",
      "Complete bed and chair transfers with consistent setup and fewer balance corrections.",
      "Maintain trunk control and confidence. Sample protocol: transfer components, supported balance, environmental setup and fatigue-aware home practice.",
      100,
      380,
      "SARA",
      "22 points",
      "21 points",
      "20 points",
      scenario(
        "Young adult with Friedreich ataxia using a wheelchair for community mobility and standing for selected transfers.",
        "Trunk oscillation and variable foot placement increase transfer time, particularly after travel or prolonged activity.",
        "The person wants predictable transfers for overnight visits and greater control over assistance.",
        "Home equipment is stable, while other settings have different surface heights and fewer grab points.",
        "Maintenance with improved strategy may be clinically meaningful even if an impairment scale changes little.",
        "Track setup, assistance, corrections, effort, surface height and carryover to unfamiliar settings.",
        "ataxia",
        "Body function: coordination and trunk control; activity: transfers; participation: visiting and independent living; environment: surface height, supports and travel fatigue.",
        "Use the assessed transfer method and review cardiac, fatigue, falls or equipment concerns through the specialist pathway.",
        "Ataxia and community rehabilitation team",
      ),
    ],
    [
      "Case 60 · HSP Community Gait",
      "Hereditary spastic paraplegia",
      "Outpatient",
      "Gait",
      "In progress",
      "Walk between transport and workplace with reliable foot clearance and planned recovery.",
      "Optimise aid use and reduce near-trips. Sample protocol: task-specific gait intervals, assistive-device review, turning and surface practice with fatigue monitoring.",
      120,
      560,
      "10MWT",
      "0.48 m/s",
      "0.55 m/s",
      "0.65 m/s",
      scenario(
        "Working-age adult with hereditary spastic paraplegia using a walking aid for community distances.",
        "Foot clearance and step timing decline with distance, while short clinic walks understate transport-to-work demands.",
        "The goal is a predictable commute-to-desk routine without repeated near-trips or excessive recovery.",
        "The route includes a ramp, lift and crowded entrance; a wheeled alternative is available for unusually demanding days.",
        "Speed, safety, device choice and recovery may move in different directions and should not be collapsed into one score.",
        "Record distance, aid, surface, foot-clearance errors, rest, confidence and post-journey function.",
        "hsp",
        "Body function: tone, selective control and endurance; activity: community walking; participation: employment; environment: route, crowding and mobility options.",
        "Review falls, pain, orthotic or aid fit and sustained functional change with the specialist team.",
        "Neurological gait and orthotic team",
      ),
    ],
    [
      "Case 61 · Vestibular Gaze Stability",
      "Vestibular hypofunction",
      "Outpatient",
      "Balance",
      "Improving",
      "Walk through visually complex environments while maintaining stable gaze and manageable symptoms.",
      "Improve head-movement tolerance and balance confidence. Sample protocol: clinician-prescribed gaze-stability tasks, graded walking exposure and symptom/recovery logging.",
      90,
      300,
      "Dizziness Handicap Inventory",
      "54 points",
      "38 points",
      "24 points",
      scenario(
        "Adult with objectively assessed unilateral peripheral vestibular hypofunction attending specialist outpatient rehabilitation.",
        "Head turns and visually busy aisles provoke gaze instability and imbalance, while straight walking in quiet spaces is reliable.",
        "The person wants to shop independently and use public spaces without avoiding necessary head movement.",
        "A quiet-to-busy exposure hierarchy is feasible; symptom response and recovery vary with sleep and visual load.",
        "Task dose must be interpreted with symptom increase, recovery and diagnostic scope; peripheral and central conditions are not interchangeable.",
        "Review head-movement condition, visual complexity, balance, symptom response, recovery time and participation.",
        "vestibular",
        "Body function: gaze stability and vestibular balance; activity: walking with head movement; participation: shopping and community access; environment: visual motion and crowding.",
        "Use only specialist-prescribed vestibular tasks and review atypical, new or worsening neurological symptoms through the clinical pathway.",
        "Vestibular rehabilitation service",
      ),
    ],
    [
      "Case 62 · Persistent Dizziness Participation",
      "Persistent postural-perceptual dizziness",
      "Outpatient",
      "Balance",
      "In progress",
      "Resume a graded mix of standing, walking and visually demanding daily activities.",
      "Reduce avoidance while maintaining predictable recovery. Sample protocol: individualised exposure hierarchy, balance tasks, pacing and interdisciplinary review.",
      85,
      280,
      "Activities-specific Balance Confidence",
      "38%",
      "49%",
      "70%",
      scenario(
        "Adult with persistent dizziness diagnosed through a specialist pathway and referred for interdisciplinary rehabilitation.",
        "Symptoms increase with prolonged standing, scrolling visual scenes and busy environments despite adequate basic strength.",
        "The person wants to return to grocery shopping and a part-time public-facing role.",
        "Home practice is possible, while work exposure and transport add visual and postural demands that need separate tracking.",
        "Symptom presence does not by itself indicate harm, but progression and interpretation must stay within the individual clinical formulation.",
        "Track exposure context, confidence, symptom response, recovery, avoidance and real-world participation.",
        "pppd",
        "Body function: visual-postural processing; activity: standing and walking in complex scenes; participation: shopping and work; environment: visual motion and duration.",
        "Follow the specialist interdisciplinary plan and review new, atypical or escalating neurological or balance findings.",
        "Vestibular and interdisciplinary rehabilitation team",
      ),
    ],
    [
      "Case 63 · Neuropathy Low-Light Balance",
      "Peripheral neuropathy",
      "Home programme",
      "Balance",
      "In progress",
      "Move safely between essential home areas when visual information is reduced.",
      "Improve compensatory strategy use and environmental consistency. Sample protocol: supported balance tasks, foot-placement practice, lighting review and route rehearsal.",
      95,
      360,
      "Functional Gait Assessment",
      "13 points",
      "16 points",
      "21 points",
      scenario(
        "Older adult with distal sensory loss and recurrent unsteadiness in low-light home conditions.",
        "Daytime indoor walking is independent, while reduced visual input and uneven thresholds increase foot-placement errors.",
        "The priority is reliable bedroom-to-bathroom access and confidence during early-morning routines.",
        "Lighting can be improved, a rail is available on part of the route and footwear varies between daytime and night.",
        "Balance performance depends strongly on vision, surface and footwear, so clinic conditions must be recorded before comparison.",
        "Review lighting, footwear, surface, aid use, foot clearance, confidence and near-fall reports.",
        "peripheral-neuropathy",
        "Body function: distal sensation and balance; activity: low-light walking; participation: private self-care; environment: lighting, thresholds, rail and footwear.",
        "Complete environmental and falls review, protect insensate skin and escalate new weakness, wounds or rapid change.",
        "Falls, podiatry and community rehabilitation team",
      ),
    ],
    [
      "Case 64 · FND Gait Retraining",
      "Functional neurological disorder",
      "Outpatient",
      "Gait",
      "In progress",
      "Increase automatic, goal-directed walking for meaningful daily routes.",
      "Reduce attention-heavy movement control and improve self-management. Sample protocol: education-consistent movement retraining, external focus, functional walking and relapse-planning review.",
      110,
      440,
      "10MWT",
      "0.36 m/s",
      "0.55 m/s",
      "0.75 m/s",
      scenario(
        "Adult with a specialist-confirmed functional neurological disorder attending coordinated outpatient rehabilitation.",
        "Walking varies substantially: deliberate step-by-step control is slow, while more automatic movement appears during selected functional tasks.",
        "The person wants to walk from home to nearby transport and manage symptom variability without abandoning activity.",
        "A consistent explanatory model has been agreed; family support is available, but conflicting advice previously increased uncertainty.",
        "Variability is clinically informative and should not be framed as lack of effort; outcome interpretation must remain formulation-led.",
        "Review automatic versus attention-focused conditions, function, confidence, fatigue, strategies and carryover.",
        "fnd",
        "Body function: functional motor control and attention; activity: walking; participation: transport and community life; environment: explanatory consistency and support.",
        "Keep rehabilitation aligned with the specialist diagnosis and shared formulation; review new or materially different neurological findings appropriately.",
        "FND multidisciplinary rehabilitation team",
      ),
    ],
    [
      "Case 65 · Transverse Myelitis Gait",
      "Transverse myelitis",
      "Subacute",
      "Gait",
      "Improving",
      "Walk a consistent household circuit with the selected aid and planned rests.",
      "Improve step clearance and standing tolerance. Sample protocol: assisted gait intervals, task-specific strengthening, transfer practice and fatigue/autonomic context logging.",
      145,
      700,
      "10MWT",
      "0.24 m/s",
      "0.39 m/s",
      "0.58 m/s",
      scenario(
        "Adult in subacute rehabilitation after transverse myelitis with incomplete lower-limb recovery.",
        "Standing and short assisted walking are possible, while endurance, sensory feedback and day-to-day consistency remain limited.",
        "The immediate goal is essential household mobility with a dependable alternative for longer distances.",
        "The home is single-level and can accommodate an aid; caregiver availability and bathroom timing influence practice relevance.",
        "Walking gains should not obscure transfer, bladder/bowel routine, fatigue, skin and wheeled-mobility needs.",
        "Track aid, assistance, foot clearance, distance, rest, autonomic symptoms and next-task tolerance.",
        "transverse-myelitis",
        "Body function: lower-limb motor and sensory control; activity: walking and transfers; participation: home routine; environment: layout, aids and caregiver timing.",
        "Follow neurological, autonomic, skin and falls plans; escalate new or worsening symptoms through the specialist pathway.",
        "Specialist neurorehabilitation team",
      ),
    ],
    [
      "Case 66 · Spina Bifida Independent Living",
      "Spina bifida",
      "Home programme",
      "ADL / participation",
      "In progress",
      "Complete an independent-living morning sequence using accessible storage, wheeled mobility and planned supports.",
      "Improve task organisation and reduce unnecessary transfer demand. Sample protocol: routine mapping, environmental adaptation, wheelchair skills and assistive-technology rehearsal.",
      100,
      360,
      "COPM performance",
      "4/10",
      "6/10",
      "8/10",
      scenario(
        "Young adult with spina bifida preparing to move from a family home into supported independent accommodation.",
        "Core self-care tasks are understood, but storage height, equipment setup and time management currently prompt family assistance.",
        "The person prioritises a private morning routine, education attendance and directing support when it is needed.",
        "The future apartment is accessible but unfamiliar; equipment maintenance, transport and personal-assistance schedules require coordination.",
        "Success includes self-direction and environmental fit, not only physical independence in every task component.",
        "Review sequence, setup, assistance directed, time, fatigue, equipment and transfer demand.",
        "spina-bifida",
        "Body function: motor, sensory and executive demands; activity: self-care and wheelchair mobility; participation: independent living and education; environment: storage, equipment and scheduled support.",
        "Use established skin, equipment and transfer plans and coordinate changes with the spina bifida and community support teams.",
        "Spina bifida transition and community team",
      ),
    ],
    [
      "Case 67 · Polytrauma Home Entry",
      "Complex traumatic injury",
      "Outpatient",
      "Functional task practice",
      "In progress",
      "Enter and leave the home using the agreed mobility method and minimal assistance.",
      "Coordinate strength, balance and equipment across a constrained entrance. Sample protocol: component practice, aid setup, graded step simulation and real-environment review.",
      135,
      520,
      "Patient-Specific Functional Scale",
      "2/10",
      "5/10",
      "8/10",
      scenario(
        "Adult recovering from complex lower-limb and upper-limb traumatic injuries after acute and inpatient care.",
        "Indoor mobility is improving, but one entrance step, limited rail access and temporary upper-limb load restrictions complicate home access.",
        "The shared priority is dependable access for appointments and family activities without an exhausting improvised routine.",
        "A temporary ramp option and different walking aids are under assessment; household space and helper availability are limited.",
        "Each injury, precaution and device affects the others, so a single gait or strength measure cannot represent the task.",
        "Review current restrictions, aid, assistance, pain, sequence, environment and post-task recovery.",
        "traumatic-injury",
        "Body function: multi-region strength, range and pain; activity: step and entrance negotiation; participation: healthcare and family access; environment: step, rail, ramp and helpers.",
        "Confirm current surgical and weight-bearing boundaries before every progression and use the documented home-access plan.",
        "Trauma rehabilitation multidisciplinary team",
      ),
    ],
    [
      "Case 68 · Upper-Limb Prosthetic Use",
      "Limb loss rehabilitation",
      "Outpatient",
      "Upper limb",
      "In progress",
      "Use a prosthetic option to stabilise and manipulate objects during selected bimanual daily tasks.",
      "Improve device choice, comfort and efficient task strategy. Sample protocol: prosthetic control practice, bimanual task analysis, socket/interface review and home carryover.",
      115,
      540,
      "COPM performance",
      "3/10",
      "5/10",
      "8/10",
      scenario(
        "Adult in specialist rehabilitation after unilateral upper-limb loss, trialling more than one prosthetic configuration.",
        "Basic control is emerging, but device comfort, visual attention and task setup determine whether the prosthesis adds functional value.",
        "Chosen priorities are food preparation, carrying work materials and one leisure task rather than universal device use.",
        "Clinic tools are accessible; home and workplace objects differ in size, weight and available surface support.",
        "More wear time or repetitions are not automatically better if comfort, skin, task efficiency or personal preference worsen.",
        "Review task choice, device configuration, control accuracy, comfort, skin/interface response and spontaneous use.",
        "limb-loss",
        "Body function: upper-limb control and interface tolerance; activity: bimanual object use; participation: home, work and leisure; environment: device configuration and object demands.",
        "Follow prosthetic-service guidance, inspect the interface as instructed and stop for skin, fit, pain or device concerns.",
        "Specialist prosthetic and upper-limb rehabilitation team",
      ),
    ],
    [
      "Case 69 · Peripheral Nerve Hand",
      "Peripheral nerve injury",
      "Outpatient",
      "Upper limb",
      "Improving",
      "Recover protected hand use for light work and household manipulation within current surgical boundaries.",
      "Improve motor control and sensory safety. Sample protocol: protected movement, graded manipulation, sensory re-education and task-specific work simulation.",
      105,
      500,
      "QuickDASH functional score",
      "64 points",
      "48 points",
      "30 points",
      scenario(
        "Working-age adult receiving coordinated surgical and rehabilitation follow-up after peripheral nerve injury to the upper limb.",
        "Selective movement is returning, while sensation, endurance and precision remain insufficient for unrestricted tool handling.",
        "The person aims to resume modified light duties and independent meal preparation before heavier tasks are considered.",
        "Protective equipment and workplace modifications are available, but productivity expectations and sensory safety need alignment.",
        "Recovery timing is biologically constrained and uneven; higher practice volume should not override protection or tissue status.",
        "Review current restrictions, movement quality, sensation, object demands, fatigue and work-task accuracy.",
        "nerve-injury",
        "Body function: peripheral motor and sensory recovery; activity: hand manipulation; participation: modified work and domestic tasks; environment: tools, protection and workplace expectations.",
        "Follow the surgical and hand-therapy protocol exactly and escalate new pain, swelling, sensory loss or wound/interface concerns.",
        "Hand surgery and rehabilitation team",
      ),
    ],
    [
      "Case 70 · Hip Fracture Home Recovery",
      "Hip fracture rehabilitation",
      "Community",
      "Gait",
      "Improving",
      "Regain safe room-to-room mobility and essential home transfers after hip fracture.",
      "Improve confidence, strength and return toward the pre-fracture residence routine. Sample protocol: frequent functional mobility, transfer practice, progressive strengthening and falls-context review.",
      140,
      560,
      "5x Sit-to-Stand",
      "42 sec",
      "34 sec",
      "26 sec",
      scenario(
        "Older adult receiving coordinated community rehabilitation after surgical management of a hip fracture.",
        "Walking with an aid and supervised transfers are possible, but pain, confidence and unfamiliar equipment slow the home routine.",
        "The priorities are bathroom access, meal-area mobility and returning to the pre-fracture living arrangement.",
        "Family support is time-limited; the home includes a narrow turn and a chair lower than the ward practice surface.",
        "Mobility recovery interacts with cognition, falls risk, medication, nutrition, equipment and social support.",
        "Review aid, assistance, pain, transfer surface, cognition/context, falls concerns and daily participation.",
        "hip-fracture",
        "Body function: lower-limb strength, pain and balance; activity: walking and transfers; participation: return home; environment: furniture, aid and support availability.",
        "Follow current weight-bearing and orthogeriatric plans, and escalate falls, delirium-like change, wound or medical concerns.",
        "Orthogeriatric and community rehabilitation team",
      ),
    ],
    [
      "Case 71 · Post-Critical Illness Recovery",
      "Post-critical illness rehabilitation",
      "Outpatient",
      "Mixed programme",
      "Improving",
      "Complete a sustainable home-and-community morning routine after prolonged critical illness.",
      "Rebuild mobility, self-care and cognitive endurance. Sample protocol: individualised functional circuit, rest planning, supported self-management and staged participation review.",
      110,
      420,
      "6MWT",
      "145 m",
      "205 m",
      "300 m",
      scenario(
        "Adult referred after a prolonged critical-care admission with combined weakness, fatigue and reduced concentration.",
        "Short indoor tasks are independent, but showering, stairs and planning appointments together exceed the current endurance window.",
        "The person wants to manage the morning routine and attend one community appointment without losing the rest of the day.",
        "A family member can assist temporarily; transport, stairs and multiple follow-up appointments add physical and cognitive load.",
        "Physical and non-physical morbidity may progress differently, and a walking gain alone does not establish readiness for the full routine.",
        "Review mobility, self-care, cognition, breathlessness, fatigue, recovery, equipment and handover needs.",
        "critical-illness",
        "Body function: global strength, endurance and cognition; activity: self-care, stairs and planning; participation: community healthcare and home life; environment: support, transport and follow-up load.",
        "Use the individualised post-critical-illness plan and escalate new cardiorespiratory, neurological or functional concerns to the clinical team.",
        "Post-critical-care multidisciplinary rehabilitation team",
      ),
    ],
    [
      "Case 72 · Cancer Participation Recovery",
      "Cancer rehabilitation",
      "Community",
      "Mixed programme",
      "In progress",
      "Resume a personally meaningful weekly routine using flexible activity and recovery planning.",
      "Improve confidence with daily mobility and task participation. Sample protocol: symptom-aware functional activity, strength and balance components, pacing and coordination with the oncology plan.",
      95,
      340,
      "Patient-specific goal rating",
      "3/10",
      "5/10",
      "8/10",
      scenario(
        "Adult referred for rehabilitation during recovery from cancer treatment, with medical clearance for an individualised programme.",
        "Fatigue, reduced strength and variable appointment burden limit errands, meal preparation and a valued social activity.",
        "The person prioritises participating in one weekly community activity while maintaining essential home tasks.",
        "Treatment schedules, transport and family support vary; a home option is needed when attendance is not feasible.",
        "Fatigue and function are influenced by treatment and medical factors, so dose patterns must never be interpreted in isolation.",
        "Review medical context supplied by the oncology team, activity, symptoms, recovery, participation and changing support needs.",
        "cancer-rehab",
        "Body function: endurance, strength and treatment-related symptoms; activity: mobility and domestic tasks; participation: social and community routine; environment: appointments, transport and support.",
        "Stay within oncology and rehabilitation clearance, and promptly refer new or worsening medical symptoms to the treating team.",
        "Oncology and rehabilitation multidisciplinary team",
      ),
    ],
  ];

  const diverseLabels = new Set(diverseCases.map((row) => row[0]));
  const existingLabels = new Set(CASES.map((row) => row[0]));
  diverseCases.forEach((row) => {
    if (!existingLabels.has(row[0])) CASES.push(row);
  });

  function mergeDiverseSample() {
    if (
      typeof state === "undefined" ||
      typeof sample !== "function" ||
      !Array.isArray(state?.cases) ||
      !state.cases.length ||
      state.cases.some((entry) => diverseLabels.has(entry.label))
    )
      return false;

    const baselineIds = Array.from(
      { length: 36 },
      (_, index) => `case-${String(index + 1).padStart(2, "0")}`,
    );
    const looksLikePriorSample = baselineIds.every((id) =>
      state.cases.some((entry) => entry.id === id),
    );
    if (!looksLikePriorSample) return false;

    const seeded = sample();
    const additions = seeded.cases.filter((entry) => diverseLabels.has(entry.label));
    const addedIds = new Set(additions.map((entry) => entry.id));
    const existingIds = new Set(state.cases.map((entry) => entry.id));
    if (additions.some((entry) => existingIds.has(entry.id))) return false;

    state.cases.push(...additions);
    state.sessions.push(
      ...seeded.sessions.filter((entry) => addedIds.has(entry.caseId)),
    );
    state.outcomes.push(
      ...seeded.outcomes.filter((entry) => addedIds.has(entry.caseId)),
    );
    return true;
  }

  const merged = mergeDiverseSample();
  if (merged && typeof save === "function") save();

  document.addEventListener("DOMContentLoaded", () => {
    if (state?.cases?.length === 72 && typeof status === "function") {
      status(
        "Loaded 72 synthetic rehabilitation cases, including 36 alternative evidence-informed scenarios.",
      );
    }

    $("loadSampleBtn")?.addEventListener("click", () => {
      if (state?.cases?.length === 72 && typeof status === "function") {
        status(
          "Loaded 72 synthetic rehabilitation cases, 216 sessions and 144 outcomes.",
        );
      }
    });

    $("clearBtn")?.addEventListener("click", () => {
      if (!state?.cases?.length && typeof status === "function") {
        status(
          "Local data cleared. Click Load sample to restore the 72 synthetic cases.",
        );
      }
    });
  });
})();
